### PR TITLE
0.9.1

### LINKED ISSUE #15: Element not visible
Hi, I'm using your python module for finding keywords from database (I have some information about companies without theirs url - roughly 2k?) but after some time of finding I get selenium.common.exceptions.ElementNotVisibleException: Message: element not visible error. I'm using Chrome for scraping. This means that I have many googledriver running process which do not end. Google blocked me or is there another fault?

And I find two small bugs which are already in GoogleScraper:
- Selenium gecko driver process never end, there is some quit error
- Google Chrome in selenium mode doesn't start by root (needed --no-sandbox option)

### PR DESCRIPTION
**Pull request by ecoron**
possible changes and fixes #15, #17, #18

### CODE REVIEW

**Comment by ihopethiswillfi** [comment]
I will likely be able to test this in the next 2 days and will let you know how it goes.

**Comment by ecoron** [comment]
thx, this helps a lot.
i think it needs much more work to make the usage of many workers and proxies stable.

**Comment by ihopethiswillfi** [comment]
Hi Ecoron

Here's a full log of a run with the latest commit ( b08e83f0545c39ec740bf475968fd79fa8823b72 ) and 99 proxies.  Hope this helps.

http://magicdata.eu/public/2017-09-14%2008:28:44_log.txt

**Comment by ecoron** [comment]
thx for testing and sharing. a lot of helpfull informations.
 i will focus on it in 0.9.2 and try to solve this challenge.

**Pull request merged**
